services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: safe
      POSTGRES_PASSWORD: safe
      POSTGRES_DB: safe-db
    ports:
      - "5433:5432" # make sure this port does not conflict with other Postgres instances
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared-db

volumes:
  pgdata:

networks:
  shared-db:
    name: shared-db
    external: true
